---
# tasks file for sample_role
- name: Install Docker
  package:
    name: "docker"
    state: "present"
  notify: restart docker

# - name: Ensure Docker is started and enabled at boot.
#   service:
#     name: docker
#     state: "started"
#     enabled: "true"

# - name: deploy nginx docker container
#   docker_container:
#     image: nginx:stable
#     name: nginx
#     state: started
#     auto_remove: true
#     ports:
#       - "8080:80"

- name: Daemonize container
  copy:
    src: web.service
    dest: '/etc/systemd/system/web.service'
    mode: 0644
  notify: daemon reload

- name: start web service
  service:
    name: web
    state: started
    enabled: yes